package game.control.robot.rovers.config;

public interface BoardConfig {

	enum INT_CONFIG_ENTRY {
		
		DEFAULT_PLANET_WIDTH(10),
		DEFAULT_PLANET_HEIGHT(10),
		
		ROVER_CARGO_MAX_LOAD(3),
		ROVER_MAX_BATTERIES(10),
		BATTERY_CAPACITY(1000),
		BATTERY_WEIGHT(1),
		ROVER_MAX_LOAD(13),
		MOTHER_SHIP_MAX_LOAD(200),
		
		CHARGING_STATION_ACCESS_POINTS(4),
		
		ROVER_MOVE_AREA_MIN_ENERGY(0),
		ROVER_MOVE_AREA_MAX_ENERGY(50),
		ROVER_MOVE_WEIGHT_MULTIPLIER(5),
		
		DROP_CARGO_ENERGY(10),
		DROP_BATTERY_ENERGY(10),
		
		COLLECT_BATTERY_CONST_ENERGY(25),
		COLLECT_BATTERY_WEIGHT_MULTIPLIER(5),
		
		COLLECTING_ROCKS_ENERGY_PER_KG(5),
		
		MARKER_ENERGY_PER_CHAR(1),
		
		CHARGE_ROVER_CONNECTION_ENERGY(15),
		CHARGE_ROVER_TRANSFER_ENERGY_PERCENT(95),
		CHARGING_STATION_CONNECTION_ENERGY(15),
		DISTRIBUTE_ENERGY_TRANSFER_PERCENT(95),
		
		SCAN_ENERGY(100),
		
		LOAD_CARGO_TO_MOTHER_SHIP_ENERGY(50),
		ENTER_MOTHER_SHIP_ENERGY(50),
		LAUNCH_MOTHER_SHIP_OUTSIDE_ENERGY(40),
		LAUNCH_MOTHER_SHIP_INSIDE_ENERGY(5);
		
		public int defaultValue;
		
		private INT_CONFIG_ENTRY(int defaultValue) {
			
			this.defaultValue = defaultValue;
			
		}
	}
	
	enum STRING_CONFIG_ENTRY {
		
		MESSAGE_SEPARATOR("\n");
		
		public String defaultValue;
		
		private STRING_CONFIG_ENTRY(String defaultValue) {
			
			this.defaultValue = defaultValue;
			
		}
		
	}

	public int getIntValue(INT_CONFIG_ENTRY entry);
	
	public String getStringValue(STRING_CONFIG_ENTRY entry);

}
